name: 🌱 SGID on ArcGIS addition
description: Share your existing data with the SGID on ArcGIS.
title: 🌱 Request for sharing with the SGID on ArcGIS
labels: ["introduction", "porter"]
assignees:
  - stdavis
  - ZachBeck
  - rkelson
body:
  - type: markdown
    attributes:
      value: >
        Incorporating data into the SGID on ArcGIS is a great way to be a part of and help improve the awesome statewide
        product that is the SGID. Data in the SGID on ArcGIS is available for all Esri users.


        Please use this form to introduce your data, answering questions like where does it comes from and why do
        you think it's a good addition.


        > [!WARNING]

        > Data additions to the SGID on ArcGIS are required to be sourced in ArcGIS Online.
  - type: input
    id: name
    attributes:
      label: Dataset Name
      description: What is the dataset's display name or title?
      placeholder: ex. Utah Address Points
    validations:
      required: true
  - type: input
    id: source
    attributes:
      label: ArcGIS Online url
      description: Where is the ArcGIS Online item url?
      placeholder: ex. https://<orgname>.maps.arcgis.com/home/item.html?id=<itemid>
    validations:
      required: true
  - type: input
    id: user
    attributes:
      label: ArcGIS Online owner name
      description: What ArcGIS Online person owns the data?
      placeholder: ex. UGRC
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: SGID category
      multiple: true
      description: What categories do you think the data best fits into? Please select up to two categories.
      options:
        - Address
        - Aerial-Photography
        - Bioscience
        - Boundaries
        - Cadastre
        - Climate
        - Contours
        - Demographic
        - Economy
        - Elevation
        - Emergency
        - Energy
        - Environment
        - Farming
        - Geoscience
        - Health
        - History
        - Indices
        - Location
        - Planning
        - Political
        - Recreation
        - Society
        - Topo
        - Transportation
        - Utilities
        - Water
      default: 0
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Primary dataset contact
      description: Who is the primary contact?
      placeholder: ex. me, John Smith
    validations:
      required: true
  - type: dropdown
    id: update
    attributes:
      label: Update frequency
      description: How often is the data updated?
      options:
        - Daily
        - Weekly
        - Monthly
        - Quarterly
        - Semi-annually
        - Annually
        - Static
        - Other
      default: 0
    validations:
      required: true
  - type: input
    id: update-other
    attributes:
      label: Other value
      description: What update schedule does your data fit in to?
      placeholder: ex. As needed
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Data description
      description: Explain the data in 1-3 sentences as if we were in 5th grade
      placeholder: ex. Polygons representing areas to encourage economic growth by providing tax breaks to development projects.
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Other information
      description: Is there anything else you would like to say?
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: SGID on ArcGIS qualifications
      description: By submitting this issue, you agree to have read the SGID on ArcGIS [qualifications](https://gis.utah.gov/documentation/policy/sgid/#sgid-on-arcgis-qualifications) and the SGID [sharing](https://gis.utah.gov/documentation/sgid/sharing/) documentation.
      options:
        - label: This data meets the SGID on ArcGIS qualifications
          required: true
        - label: I have read the SGID sharing documentation
          required: true
  - type: markdown
    attributes:
      value: |
        > [!Tip]
        > 🙈🙈🙈 Please ignore everything below this line.
  - type: input
    id: type
    attributes:
      label: <!---->
      value: <!-- porter = {"type":"sgid-on-arcgis"} -->
    validations:
      required: true
